apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
  labels:
    app: mongo-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      imagePullSecrets:
         - name: docker-creds
      containers:
        - name: mongo-express
          image: mongo-express: 1.0.2
          ports:
            - containerPort: 8081
          env:
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-root-username
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-root-password
            - name: ME_CONFIG_MONGODB_SERVER
              value: mongodb-service
            # Optional: show DB name in UI title
            - name: ME_CONFIG_SITE_BASEURL
              value: /
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-express-service
  labels:
    app: mongo-express
spec:
  type: LoadBalancer
  loadBalancerIP: 10.48.229.45        # <- specific MetalLB IP
  selector:
    app: mongo-express
  ports:
    - name: http
      port: 8081
      targetPort: 8081
      protocol: TCP
  externalTrafficPolicy: Cluster       

